stages:
  clean_data:
    cmd: python -m german_credit_ml.clean --config params.yaml
    deps:
    - data/raw/german_credit_modified.csv
    - german_credit_ml/clean.py
    params:
    - data_load.processed
    - data_load.raw
    outs:
    - data/processed/german_credit_clean.csv
  eda:
    cmd: python -m german_credit_ml.eda --input-data 
      data/processed/german_credit_clean.csv --output-dir reports/figures
    deps:
    - data/processed/german_credit_clean.csv
    - german_credit_ml/eda.py
    params:
    - data_load.figures
    - data_load.processed
