# params.yaml
#data_load:
#  raw: data/raw/german_credit_modified.csv
#  processed: data/processed/german_credit_clean.csv
#  figures: reports/figures

#train:
#  test_size: 0.2
#  random_state: 42
#  n_iter_search: 25
#  model_output: models/xgboost_model_prueba.pkl # <-- CAMBIA .joblib por .pkl
#  metrics_output: reports/metrics.json
#  plots_output: reports/figures/training

#OOP
data:
  path: data/raw/german_credit_modified_cleaned.csv
  target: credit_risk
  test_size: 0.2
  random_state: 42

model:
  type: RandomForestClassifier
  class_weight: balanced
  n_jobs: -1

tuning:
  cv: 5
  param_grid:
    n_estimators: [100, 300]
    max_depth: [None, 6, 12]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]

mlflow:
  experiment: "fase1_modelado_equipo46"
  run_name: "rf_gridcv_baseline"
  tracking_uri: null
  register_model: "credit_risk_rf"
  register_alias: "staging"
